export const words = [
  "burrata",
  "mascarpone",
  "parmesan",
  "halloumi",
  "gruyere cheese",
  "camembert",
  "grana padano",
  "pecorino romano",
  "emmental cheese",
  "taleggio",
  "roquefort",
  "fontina",
  "buffalo mozzarella",
  "comte",
  "stilton",
  "tete de moine",
  "caciocavallo",
  "fromage blanc",
  "epoisses",
  "mimolette",
  "brunost",
  "morbier",
  "fourme d ambert",
  "brillat savarin",
  "tilsit",
  "tomme de savoie",
  "castelmagno",
  "delice de bourgogne",
  "ossau iraty",
  "formager d affinois",
  "crottin de chavignol",
  "manouri"
]

